### ISSUE TITLE
Issues with 'make up' command in Ubuntu 20.0.4

### ISSUE THREAD

**Issue by promana01** [IDMEFv2/IDMEFv2-prototype#2]
Hello,
I have been trying to execute the 'make up' for testing the software, but the process seems to fail.
I paste the full log of the installation process for checking.
The system is an Ubuntu 20.0.4.

root@ubuntu-s-1vcpu-1gb-35gb-intel-sfo3-01:/home/idi01/proy/IDMEFv2-prototype# make up
sudo mkdir -pv elasticsearch_data elasticsearch_logs kafka_logs
mkdir: created directory 'elasticsearch_data'
mkdir: created directory 'elasticsearch_logs'
mkdir: created directory 'kafka_logs'
sudo chown -R 1000:0 elasticsearch_data elasticsearch_logs
(sudo podman-compose -p proto -f docker-compose.yml up 2>&1 1>>logs &)
root@ubuntu-s-1vcpu-1gb-35gb-intel-sfo3-01:/home/idi01/proy/IDMEFv2-prototype# podman-compose version: 1.0.7
['podman', '--version', '']
using podman version: 3.4.4
** excluding:  set()
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'proto_setup']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'proto_postgres']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'proto_es01']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'proto_zoo1']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'proto_kafka1']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'proto_kafdrop']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'proto_gui']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'proto_logstash']
podman build -f /home/idi01/proy/IDMEFv2-prototype/postgres/Dockerfile -t proto_postgres --env POSTGRES_USER=postgres --env POSTGRES_PASSWORD=changeme --env PGDATA=/data/postgres /home/idi01/proy/IDMEFv2-prototype/postgres
podman build -f /home/idi01/proy/IDMEFv2-prototype/setup/Dockerfile -t proto_setup --build-arg ELASTIC_VERSION=8.6.1 /home/idi01/proy/IDMEFv2-prototype/setup
podman build -f /home/idi01/proy/IDMEFv2-prototype/elasticsearch/Dockerfile -t proto_es01 --ulimit memlock=-1:-1 --env ES_JAVA_OPTS=-Xms512m -Xmx512m --env ELASTIC_PASSWORD=elastic --build-arg ELASTIC_VERSION=8.6.1 /home/idi01/proy/IDMEFv2-prototype/elasticsearch
podman build -f /home/idi01/proy/IDMEFv2-prototype/zoo/Dockerfile -t proto_zoo1 --env ZOOKEEPER_CLIENT_PORT=2181 --env ZOOKEEPER_SERVER_ID=1 --env ZOOKEEPER_SERVERS=zoo1:2888:3888 --build-arg ZOO_VERSION=7.3.2 /home/idi01/proy/IDMEFv2-prototype/zoo
podman build -f /home/idi01/proy/IDMEFv2-prototype/kafka/Dockerfile -t proto_kafka1 --env KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka1:19092,EXTERNAL://kafka1:9092,DOCKER://kafka1:29092 --env KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT --env KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL --env KAFKA_ZOOKEEPER_CONNECT=zoo1:2181 --env KAFKA_BROKER_ID=1 --env KAFKA_LOG4J_LOGGERS=kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO --env KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 --env KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1 --env KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1 --env KAFKA_JMX_PORT=9999 --env KAFKA_JMX_HOSTNAME=kafka1 --env KAFKA_AUTHORIZER_CLASS_NAME=kafka.security.authorizer.AclAuthorizer --env KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true --env KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=False --build-arg KAFKA_VERSION=7.3.2 /home/idi01/proy/IDMEFv2-prototype/kafka
podman build -f /home/idi01/proy/IDMEFv2-prototype/kafdrop/Dockerfile -t proto_kafdrop --env KAFKA_BROKERCONNECT=kafka1:9092 --env JVM_OPTS=-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify --env CMD_ARGS=--server.port=9201 --build-arg KAFDROP_VERSION=3.30.0 /home/idi01/proy/IDMEFv2-prototype/kafdrop
podman build -f /home/idi01/proy/IDMEFv2-prototype/logstash/Dockerfile -t proto_logstash --env LS_JAVA_OPTS=-Xms256m -Xmx256m --env LOGSTASH_INTERNAL_PASSWORD= --env MONITORING_ENABLED=False --env MAX_MSG_SIZE=1048576 --env BOOTSTRAP_SERVER=http://kafka1:9092 --env BIG_DATA_SERVER=http://es01:9200/ --env BIG_DATA_USERNAME=elastic --env BIG_DATA_PASSWORD=elastic --env ANALYZER_NAME=Logstash --env ANALYZER_LOCATION=Safe4SOC - Prototype --env ANALYZER_UNLOCATION=FR PAR --env ANALYZER_GEOLOCATION=48.7730817, 2.2442167 --env ANALYZER_IP=192.168.1.1 --env ANALYZER_HOSTNAME= --env LISTEN_SYSLOG=6514 --env TOPIC_COLLECTED=my_collected --env TOPIC_PROCESSED=my_processed --env INDEX_ALERTS=alerts --env INDEX_LOGS=logs --build-arg LOGSTASH_VERSION=8.6.1 /home/idi01/proy/IDMEFv2-prototype/logstash
podman build -f /home/idi01/proy/IDMEFv2-prototype/gui/Dockerfile -t proto_gui /home/idi01/proy/IDMEFv2-prototype/gui

Error: unknown flag: --env
exit code: 125
Error: unknown flag: --env
exit code: 125
Error: unknown flag: --env
Error: unknown flag: --env
exit code: 125
exit code: 125
Error: unknown flag: --env
exit code: 125
Error: unknown flag: --env
exit code: 125**
+ mkdir /state
+ chmod 0775 /state
+ chown elasticsearch:root /state
debconf: delaying package configuration, since apt-utils is not installed
debconf: delaying package configuration, since apt-utils is not installed
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 2.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
exit code: 0
Cloning into 'prototype'...
error: prewikka/locale/de/LC_MESSAGES/prewikka.po:2804: placeholders are incompatible
error: prewikka/locale/pt_BR/LC_MESSAGES/prewikka.po:2397: placeholders are incompatible
error: prewikka/locale/pt_BR/LC_MESSAGES/prewikka.po:2810: placeholders are incompatible
error: prewikka/locale/ru/LC_MESSAGES/prewikka.po:168: unknown named placeholder 'version'
error: prewikka/locale/ru/LC_MESSAGES/prewikka.po:2793: placeholders are incompatible
error: prewikka/locale/pl/LC_MESSAGES/prewikka.po:2162: placeholders are incompatible
error: prewikka/locale/pl/LC_MESSAGES/prewikka.po:2854: placeholders are incompatible
error: prewikka/locale/es/LC_MESSAGES/prewikka.po:2393: placeholders are incompatible
error: prewikka/locale/es/LC_MESSAGES/prewikka.po:2807: placeholders are incompatible
9 errors encountered.
exit code: 0
['podman', 'ps', '--filter', 'label=io.podman.compose.project=proto', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
podman pod create --name=pod_proto --infra=false --share=
exit code: 0
podman volume inspect proto_setup || podman volume create proto_setup
['podman', 'volume', 'inspect', 'proto_setup']
['podman', 'network', 'exists', 'proto_proto']
podman create --name=proto_setup_1 --pod=pod_proto --label io.podman.compose.config-hash=45b5cc56a3185ac8b062336f324d55c5ee6d7244a759b3692c191fb5cb9faba2 --label io.podman.compose.project=proto --label io.podman.compose.version=1.0.7 --label PODMAN_SYSTEMD_UNIT=podman-compose@proto.service --label com.docker.compose.project=proto --label com.docker.compose.project.working_dir=/home/idi01/proy/IDMEFv2-prototype --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=setup -v /home/idi01/proy/IDMEFv2-prototype/setup/entrypoint.sh:/entrypoint.sh:Z,ro -v proto_setup:/state:Z -v /home/idi01/proy/IDMEFv2-prototype/setup/config:/config:Z,ro --net proto_proto --network-alias setup --init proto_setup
exit code: 0
podman volume inspect proto_postgres || podman volume create proto_postgres
['podman', 'volume', 'inspect', 'proto_postgres']
['podman', 'network', 'exists', 'proto_proto']
podman create --name=proto_postgres_1 --pod=pod_proto --label io.podman.compose.config-hash=45b5cc56a3185ac8b062336f324d55c5ee6d7244a759b3692c191fb5cb9faba2 --label io.podman.compose.project=proto --label io.podman.compose.version=1.0.7 --label PODMAN_SYSTEMD_UNIT=podman-compose@proto.service --label com.docker.compose.project=proto --label com.docker.compose.project.working_dir=/home/idi01/proy/IDMEFv2-prototype --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=changeme -e PGDATA=/data/postgres -v proto_postgres:/data/postgres --net proto_proto --network-alias postgres -p 5432:5432 --restart on-failure --healthcheck-command /bin/sh -c 'pg_isready -U postgres' --healthcheck-interval 5s --healthcheck-timeout 5s --healthcheck-retries 5 proto_postgres
Error: short-name "proto_postgres" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
exit code: 125
['podman', 'network', 'exists', 'proto_proto']
podman create --name=proto_es01_1 --pod=pod_proto --label io.podman.compose.config-hash=45b5cc56a3185ac8b062336f324d55c5ee6d7244a759b3692c191fb5cb9faba2 --label io.podman.compose.project=proto --label io.podman.compose.version=1.0.7 --label PODMAN_SYSTEMD_UNIT=podman-compose@proto.service --label com.docker.compose.project=proto --label com.docker.compose.project.working_dir=/home/idi01/proy/IDMEFv2-prototype --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=es01 -e ES_JAVA_OPTS=-Xms512m -Xmx512m -e ELASTIC_PASSWORD=elastic -v /home/idi01/proy/IDMEFv2-prototype/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:Z,ro -v /home/idi01/proy/IDMEFv2-prototype/elasticsearch_data:/usr/share/elasticsearch/data:Z -v /home/idi01/proy/IDMEFv2-prototype/elasticsearch_logs:/usr/share/elasticsearch/logs:Z --net proto_proto --network-alias es01 -p 9200:9200 -p 9300:9300 --ulimit memlock=-1:-1 proto_es01
Error: short-name "proto_es01" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
exit code: 125
['podman', 'network', 'exists', 'proto_proto']
podman create --name=proto_zoo1_1 --pod=pod_proto --label io.podman.compose.config-hash=45b5cc56a3185ac8b062336f324d55c5ee6d7244a759b3692c191fb5cb9faba2 --label io.podman.compose.project=proto --label io.podman.compose.version=1.0.7 --label PODMAN_SYSTEMD_UNIT=podman-compose@proto.service --label com.docker.compose.project=proto --label com.docker.compose.project.working_dir=/home/idi01/proy/IDMEFv2-prototype --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=zoo1 -e ZOOKEEPER_CLIENT_PORT=2181 -e ZOOKEEPER_SERVER_ID=1 -e ZOOKEEPER_SERVERS=zoo1:2888:3888 --net proto_proto --network-alias zoo1 -p 2181:2181 --hostname zoo1 --restart on-failure proto_zoo1
Error: short-name "proto_zoo1" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
exit code: 125
['podman', 'network', 'exists', 'proto_proto']
podman create --name=proto_kafka1_1 --pod=pod_proto --requires=proto_zoo1_1 --label io.podman.compose.config-hash=45b5cc56a3185ac8b062336f324d55c5ee6d7244a759b3692c191fb5cb9faba2 --label io.podman.compose.project=proto --label io.podman.compose.version=1.0.7 --label PODMAN_SYSTEMD_UNIT=podman-compose@proto.service --label com.docker.compose.project=proto --label com.docker.compose.project.working_dir=/home/idi01/proy/IDMEFv2-prototype --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=kafka1 -e KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka1:19092,EXTERNAL://kafka1:9092,DOCKER://kafka1:29092 -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT -e KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL -e KAFKA_ZOOKEEPER_CONNECT=zoo1:2181 -e KAFKA_BROKER_ID=1 -e KAFKA_LOG4J_LOGGERS=kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 -e KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1 -e KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1 -e KAFKA_JMX_PORT=9999 -e KAFKA_JMX_HOSTNAME=kafka1 -e KAFKA_AUTHORIZER_CLASS_NAME=kafka.security.authorizer.AclAuthorizer -e KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true -e KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=False -v /home/idi01/proy/IDMEFv2-prototype/kafka_logs:/var/lib/kafka/logs:Z --net proto_proto --network-alias kafka1 -p 9092:9092 -p 29092:29092 -p 9999:9999 --hostname kafka1 --restart on-failure proto_kafka1
Error: short-name "proto_kafka1" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
exit code: 125
['podman', 'network', 'exists', 'proto_proto']
podman create --name=proto_kafdrop_1 --pod=pod_proto --requires=proto_kafka1_1,proto_zoo1_1 --label io.podman.compose.config-hash=45b5cc56a3185ac8b062336f324d55c5ee6d7244a759b3692c191fb5cb9faba2 --label io.podman.compose.project=proto --label io.podman.compose.version=1.0.7 --label PODMAN_SYSTEMD_UNIT=podman-compose@proto.service --label com.docker.compose.project=proto --label com.docker.compose.project.working_dir=/home/idi01/proy/IDMEFv2-prototype --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=kafdrop -e KAFKA_BROKERCONNECT=kafka1:9092 -e JVM_OPTS=-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify -e CMD_ARGS=--server.port=9201 --net proto_proto --network-alias kafdrop -p 9201:9201 --restart on-failure proto_kafdrop
Error: short-name "proto_kafdrop" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
exit code: 125
['podman', 'network', 'exists', 'proto_proto']
podman create --name=proto_gui_1 --pod=pod_proto --requires=proto_postgres_1,proto_es01_1,proto_setup_1 --label io.podman.compose.config-hash=45b5cc56a3185ac8b062336f324d55c5ee6d7244a759b3692c191fb5cb9faba2 --label io.podman.compose.project=proto --label io.podman.compose.version=1.0.7 --label PODMAN_SYSTEMD_UNIT=podman-compose@proto.service --label com.docker.compose.project=proto --label com.docker.compose.project.working_dir=/home/idi01/proy/IDMEFv2-prototype --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=gui -v /home/idi01/proy/IDMEFv2-prototype/gui/entrypoint.sh:/entrypoint.sh:Z,ro -v /home/idi01/proy/IDMEFv2-prototype/gui/config/prewikka.conf:/etc/prewikka/prewikka.conf:Z,ro -v /home/idi01/proy/IDMEFv2-prototype/gui/config/auth.conf:/etc/prewikka/conf.d/auth.conf:Z,ro -v /home/idi01/proy/IDMEFv2-prototype/gui/config/idmefv2.conf:/etc/prewikka/conf.d/idmefv2.conf:Z,ro -v /home/idi01/proy/IDMEFv2-prototype/gui/config/logs.conf:/etc/prewikka/conf.d/logs.conf:Z,ro -v /home/idi01/proy/IDMEFv2-prototype/gui/config/secef.conf:/etc/prewikka/conf.d/secef.conf:Z,ro -v /home/idi01/proy/IDMEFv2-prototype/gui/config/menu.yml:/etc/prewikka/menu.yml:Z,ro -v /home/idi01/proy/IDMEFv2-prototype/gui/config/S4SOC-logo.png:/usr/local/lib/python3.11/site-packages/prewikka/htdocs/images/S4SOC-logo.png:Z,ro -v /home/idi01/proy/IDMEFv2-prototype/gui/config/secef.css:/usr/local/lib/python3.11/site-packages/prewikka/htdocs/css/themes/secef.css:Z,ro --net proto_proto --network-alias gui -p 80:80 -p 81:81 --restart on-failure proto_gui
Error: "proto_postgres_1" is not a valid container, cannot be used as a dependency: no container with name or ID "proto_postgres_1" found: no such container
exit code: 125
['podman', 'network', 'exists', 'proto_proto']
podman create --name=proto_logstash_1 --pod=pod_proto --requires=proto_kafka1_1,proto_es01_1,proto_zoo1_1 --label io.podman.compose.config-hash=45b5cc56a3185ac8b062336f324d55c5ee6d7244a759b3692c191fb5cb9faba2 --label io.podman.compose.project=proto --label io.podman.compose.version=1.0.7 --label PODMAN_SYSTEMD_UNIT=podman-compose@proto.service --label com.docker.compose.project=proto --label com.docker.compose.project.working_dir=/home/idi01/proy/IDMEFv2-prototype --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=logstash -e LS_JAVA_OPTS=-Xms256m -Xmx256m -e LOGSTASH_INTERNAL_PASSWORD= -e MONITORING_ENABLED=False -e MAX_MSG_SIZE=1048576 -e BOOTSTRAP_SERVER=http://kafka1:9092 -e BIG_DATA_SERVER=http://es01:9200/ -e BIG_DATA_USERNAME=elastic -e BIG_DATA_PASSWORD=elastic -e ANALYZER_NAME=Logstash -e ANALYZER_LOCATION=Safe4SOC - Prototype -e ANALYZER_UNLOCATION=FR PAR -e ANALYZER_GEOLOCATION=48.7730817, 2.2442167 -e ANALYZER_IP=192.168.1.1 -e ANALYZER_HOSTNAME= -e LISTEN_SYSLOG=6514 -e TOPIC_COLLECTED=my_collected -e TOPIC_PROCESSED=my_processed -e INDEX_ALERTS=alerts -e INDEX_LOGS=logs -v /home/idi01/proy/IDMEFv2-prototype/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:Z,ro -v /home/idi01/proy/IDMEFv2-prototype/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:Z,ro -v /home/idi01/proy/IDMEFv2-prototype/logstash/rules.yml:/usr/share/logstash/config/rules.yml:Z,ro -v /home/idi01/proy/IDMEFv2-prototype/logstash/IDMEFv2-light.schema:/usr/share/logstash/config/IDMEFv2-light.schema:Z,ro -v /home/idi01/proy/IDMEFv2-prototype/logstash/IDMEFv2.schema:/usr/share/logstash/config/IDMEFv2.schema:Z,ro -v /home/idi01/proy/IDMEFv2-prototype/logstash/IDMEFv2.mapping:/usr/share/logstash/config/IDMEFv2.mapping:Z,ro -v /home/idi01/proy/IDMEFv2-prototype/logstash/NXLog.schema:/usr/share/logstash/config/NXLog.schema:Z,ro -v /home/idi01/proy/IDMEFv2-prototype/logstash/pipeline:/usr/share/logstash/config/pipeline:Z,ro -v /home/idi01/proy/IDMEFv2-prototype/logstash/scripts:/usr/share/logstash/config/scripts:Z,ro --net proto_proto --network-alias logstash -p 6514:6514 proto_logstash
Error: short-name "proto_logstash" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
exit code: 125
[setup] podman start -a proto_setup_1
[postgres] podman start -a proto_postgres_1
[es01] podman start -a proto_es01_1
[zoo1] podman start -a proto_zoo1_1
[kafka1] podman start -a proto_kafka1_1
[kafdrop] podman start -a proto_kafdrop_1
[gui] podman start -a proto_gui_1
[logstash] podman start -a proto_logstash_1
[zoo1] exit code: 125
[kafka1] exit code: 125
[gui] exit code: 125
[postgres] exit code: 125
[es01] exit code: 125
[kafdrop] exit code: 125
[logstash] exit code: 125

Thank you.

**Comment by Bytes-n-AI** [comment]
It requires at least podman 4. Can you update it and retry ?

**Comment by Bytes-n-AI** [comment]
I just add a check in be792fa54080c6224a71b4d5b0674d17dbd0c28e so you will get a proper error
